version: '3'
services:

  gitsy:
    image: gitsy:latest
    container_name: gitsy-app
    environment:
      - GITHUB_API_BASE_URL_SCHEME=https
      - GITHUB_API_BASE_URL=api.github.com
      - SYNC_ORGS=productboard
      - ENABLE_SYNC=false
      - ORG_SYNC_CRON=0 0 12 1 * *
      - POSTGRES_SRC_URL=jdbc:postgresql://postgres:5432/gitsy
      - POSTGRES_USER=postgres
      - POSTGRES_PSWD=postgres
      - SPRING_PROFILES_ACTIVE=prod
      - APP_LOGGING_LEVEL=WARN
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    container_name: gitsy-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gitsy
    ports:
      - "5432:5432"
    restart: always
