version: '3'
services:

  postgres:
    image: postgres:14.5-alpine
    container_name: gitsy-postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=gitsy
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
