# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Gitsy GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build the application
    runs-on: ubuntu-latest
    steps:

      # Setup Java 17 environment for the next steps
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      # Setup Gradle tool, it also provides Gradle caching
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Assemble application code
      - name: Assemble Kotlin application
        run: ./gradlew assemble

      # Compile application tests
      - name: Compile tests
        run: ./gradlew compileTestJava compileTestKotlin

      # Cache build result to use it in another jobs
      - name: Cache build result
        uses: actions/cache@v3
        with:
          path: |
            build
            gradle
            detekt
            gradlew
            build.gradle.kts
            settings.gradle.kts
          key: build-result-cache-key

  test:
    name: Analyse and test the application
    needs: build
    runs-on: ubuntu-latest
    steps:

      # Use build from build job
      - name: Use cached build result
        uses: actions/cache@v3
        with:
          path: |
            build
            gradle
            detekt
            gradlew
            build.gradle.kts
            settings.gradle.kts
          key: build-result-cache-key

      # Setup Gradle tool, it also provides Gradle caching
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Run Detekt checking
      - name: Check with Detekt
        run: ./gradlew detekt

      # Run tests and generate coverage report
      - name: Test with coverage report
        run: ./gradlew koverReport

      # Upload generated coverage report
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: build/reports/kover/report.xml
